SendGrid and Mailjet example code
peter279k/serviceBundle pull request #9
Opened 2017-12-15 21:36 UTC by joefearnley

Hi @peter279k ,

I have added SendGrid and Mailjet example code in the README. Let me know if I missed anything.

Thanks,
Joe

2017-12-19 07:55 UTC, peter279k requested changes

2017-12-19 07:55 UTC, peter279k commented on README.md
> +  $service = (new ServiceFactory)->create('SendGrid');
The ```ServiceFactory``` missed the namespace and it should be added in the head of sample code.

2017-12-19 07:55 UTC, peter279k commented on README.md
> +  $service = (new ServiceFactory)->create('Mailjet');
The namespace is the same problem.

2017-12-19 07:59 UTC, peter279k commented
Hi @joefearnley, thank you for your PR.
I'm sorry that I cannot review right away.
And I will have twelve days of the military training from the beginning of the next week.
Please feel free to send PR and I will review them after finishing the training.

Thanks.

2017-12-20 15:13 UTC, joefearnley commented
Hi @peter279k ,

No problem, review them this when you get time. I updated this adding the namespaces to the README examples for SendGrid and Mailjet.

2018-01-18 02:09 UTC, peter279k approved these changes

2018-01-18 02:09 UTC, merged

2018-01-18 02:10 UTC, peter279k commented
I'm sorry that the review is delay.
Thank you for your PR!